### ISSUE TITLE
Firefly not intractable after profile deletion

### ISSUE THREAD

**Issue by jeliasson** [iotaledger/firefly#1630]
### Issue description

When deleting a profile, the UI (with other profile overview) becomes intractable. I can't click profiles or create a new one.  Restarting Firefly fixes the problem.

### Firefly version

v1.2.0

### OS details

Windows 11

### Can the issue be reliably reproduced?

Yes

### Steps to reproduce the issue

1. Create profile
2. Go to settings
3. Delete profile
4. Confirm
5. Try opening another profile or create a new one from the start page that will be shown.
...

### Expected behaviour

To select a profile or create a new one

### Actual behaviour

Firefly becomes non-intractable and a restart is required

**Comment by nicole-obrien** [comment]
Fixed in next update with this PR: https://github.com/iotaledger/firefly/pull/1209

**Comment by jeliasson** [comment]
@nicole-obrien When is the release due for #1209? It's been merged, and version 1.2.0 still have this issue. Thanks!
