### ISSUE TITLE
[Bug]: Error on starting Firefly and showing up wrong balance

### ISSUE THREAD

**Issue by cedricdonigarten** [iotaledger/firefly#2110]
### Issue description

Firefly starts with error. Afterwards i can see the correct amount of Iota for a couple of minutes. later on, one wallet will be reduced with 500 Iota (this was the amount of one internal transfer). Check for balance identifies the missing tokens it shows the correct amount for 2 seconds only. Only after checking a second time it shows the correct balance for a longer duration

The second photo is a couple of seconds later after i tried staking. and staking finally did not work
<img width="368" alt="image" src="https://user-images.githubusercontent.com/97615319/149176749-bd7fc38d-2347-4fa9-b13e-7acd2fe26ee3.png">

<img width="378" alt="image" src="https://user-images.githubusercontent.com/97615319/149176805-fe437b5c-d72e-44bc-b419-115e43a27b61.png">

![2022-01-12 17_16_11-Firefly](https://user-images.githubusercontent.com/97615319/149179254-d320e6f8-951b-457e-af61-cf87edb337e4.jpg)

![2022-01-12 17_16_25-Firefly](https://user-images.githubusercontent.com/97615319/149179295-8c78c6ff-d106-4e66-a983-1730f4170bf8.jpg)

App Version: 1.3.2

platform: win32
platformVersion: 10.0.19043
platformArchitecture: x64
cpuCount: 16
totalMem: 16056.5 MB
freeMem: 9953.9 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_CONNECTION_RESET

### Expected behaviour

Show up correct balance permanently 

### Actual behaviour

Firefly starts with error. Afterwards i can see the correct amount of Iota for a couple of minutes. later on, one wallet will be reduced with 500 Iota (this was the amount of one internal transfer). Check for balance identifies the missing tokens it shows the correct amount for 2 seconds only. Only after checking a second time it shows the correct balance for a longer duration

### Can the issue reliably be reproduced?

Yes

### Diagnostics

```shell
Firefly v1.3.2
Sprache: de
Währung: USD
Node-Auswahl: Manuell
Plattform: win32
Plattformversion: 10.0.19043
Plattform-Architektur: x64
CPU-Anzahl: 16
Gesamtspeicher: 16056.5 MB
Freier Speicher: 9982.1 MB
```

### Errors

```shell
App Version: 1.3.2

platform: win32
platformVersion: 10.0.19043
platformArchitecture: x64
cpuCount: 16
totalMem: 16056.5 MB
freeMem: 9953.9 MB

Error Type: Main Unhandled Promise Rejection

Error: Uncaught Error: net::ERR_CONNECTION_RESET
```
Wed, 12 Jan 2022 16:20:10 GMT
ClientError: `request or response body error: operation timed out`

Wed, 12 Jan 2022 16:20:00 GMT
ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/info): operation timed out`

Wed, 12 Jan 2022 16:19:50 GMT
ClientError: `error sending request for url (https://mainnet-node.tanglebay.com/api/v1/info): operation timed out`

Wed, 12 Jan 2022 16:17:21 GMT
ClientError: `request or response body error: operation timed out`

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MiKeF05** [comment]
Can you try to create a new profile and restore your profile?

**Comment by cedricdonigarten** [comment]
New windows profile or just removin evrything firefly related from my profile?

**Comment by nicole-obrien** [comment]
@cedricdonigarten based on the timestamps in the error log are you able to pinpoint on the timeline at what point the balance is shown and at what point it is not.

**Comment by cedricdonigarten** [comment]
> @cedricdonigarten based on the timestamps in the error log are you able to pinpoint on the timeline at what point the balance is shown and at what point it is not?

Hi, since I have re-installed firefly and imported the backup, the amount of balance shows up correct, BUT i am still not able to see the stake rewards within Firefly. But, I can see them on thetangle.org for all three wallets i now have.
Here is a screenshot of one of my wallets.
<img width="392" alt="image" src="https://user-images.githubusercontent.com/97615319/150307726-a57d50a6-b7e6-4524-ba54-a7dcb0870a44.png">

**Comment by nicole-obrien** [comment]
Fixed in latest release, forgot to link the issue

**Comment by cedricdonigarten** [comment]
Updated to v1.3.3 but still not be able to see staking rewards within FF.
![image](https://user-images.githubusercontent.com/97615319/150961754-9ea8f0a8-a19f-429c-b5d7-606591ea3573.png)
