### ISSUE TITLE
[Bug report]: Gift storage deposit for native assets not working

### ISSUE THREAD

**Issue by lennie23** [iotaledger/firefly#7325]
### Platform

Desktop

### Version

shimmer 2.1.5

### Description

I am attempting to stake my SOON tokens, however, everytime I do so the storage deposit is in my firefly shimmer is set to 49000 glow, and when I click the button to send the storage deposit as gift the amount changes to 53400, but when I attempt to send I get an error message stating the storage deposit is too low at 49000 and I need to send 53400 glow. 

I have attempted to uninstall and reinstall the app and made sure my ledger and macbook pro is up to date software but this does not change the error within firefly. 

Error message is shown in photo.

### Expected behaviour

I expected the storage deposit to be sent and not have the glow change on its own when I click the button next to storage deposit in the firefly shimmer. 

### Actual behaviour

Error message below pops up and states I am sended a lower storage deposit amount. 

### Can the issue reliably be reproduced?

Yes

### Operating System

Mac

### Developer Profile

Yes

### Profile Type

Hardware (Ledger)

### Staking

Previously staked

### Crash Status

None of the above

### Error Messages

<img width="853" alt="Screen Shot 2023-08-17 at 4 57 49 PM" src="https://github.com/iotaledger/firefly/assets/15041690/ca1a6a38-1fff-4b38-aea1-c117bea967fd">

### Duplicate declaration

- [X] I have searched the issues tracker this issue and there is none

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by begonaalvarezd** [comment]
We are working on a fix, seems like indeed we have an issue around gifting the storage deposit for native tokens and nfts, tracked in https://github.com/iotaledger/firefly/issues/7327
A small note: when you gift the storage deposit is normal that the value decreseases because the transaction has one less unlock condition, the storage deposit value change works as expected

**Comment by begonaalvarezd** [comment]
Fixed by https://github.com/iotaledger/firefly/pull/7331

**Comment by lennie23** [comment]
I tried staking my soon again and I am still experiencing the same issue.

**Comment by begonaalvarezd** [comment]
The fix is merged in the repository but is not yet included in a new production release, it wil be included in the next one which we are preparing to release soon
